### ISSUE TITLE
Diário-IgorSVieira

### ISSUE THREAD

**Issue by faber222** [mmsobral-croom/FBJ-ISV#3]
Fazer a produção e entrega do Diário de bordo 1 no moodle do professor.

**Comment by IgorSVieira** [comment]
Desenvolvimento da parte de leitura do arquivo, criação de uma fila de structs a partir de um tipo definido, separando as informações, e interação com o usuário por meio de um menu que mostra as opções a partir da quantidade de categorias fornecidas. As funções serão separadas em arquivos distintos posteriormente.

**Comment by IgorSVieira** [comment]
EM AULA: Teste da versão publicada no dia 10/05 para ter certeza de que a parte de leitura do arquivo se encontrava funcionando. Desenvolvimento das funções para colocar o cliente na fila de atendimento e para chamar um cliente respeitando o tempo ou a preferência por categoria. O código foi colocado no repositório com a parte de ordenamento de lista por preferência a ser finalizado, apresentando também um erro na numeração das senhas (sempre colocava o número 1).

**Comment by IgorSVieira** [comment]
APÓS A AULA: Finalização do ordenamento de lista por preferência e correção do erro na numeração das senhas. Foi criada uma nova fila de structs para salvar as senhas a partir das categorias de atendimento predefinidas em arquivo csv. Um falha de segmentação foi percebida e foi corrigida. Ao retirar um item da lista o iterador não estava recebendo a nova posição.

Com isso, considerando também as modificações feitas pelo @faber222 , temos o código funcionando!
